# environment.yml
name: quantAgent
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.7
  - cudatoolkit=11.8
  - pytorch::faiss-gpu
  - pip
  - pip:
      - -r requirements.txt